server:
  port: 8080

spring:
  application:
    name: backend-coding-challenge
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
